export const SET_ACTIVE_USER_ID = "SET_ACTIVE_USER_ID"
export const SET_VALUE_TYPE = "SET_VALUE_TYPE"
export const SEND_MESSAGE = "SEND_MESSAGE"

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";